### ISSUE TITLE
Add the ability to blackhole domains

### ISSUE THREAD

**Issue by miketweaver** [lancachenet/sniproxy#12]
There is an issue with comcast where steam uses HTTPS to download files. 

This can be easily fixed in sniproxy by adding the ability to blackhole domains.

Here's an example of a ` /etc/sniproxy.conf` file with `edge.steam-dns.top.comcast.net` blackholed:

```
user nobody

pidfile /var/run/sniproxy.pid

resolver {
        nameserver 8.8.8.8 8.8.4.4
        mode ipv4_only
}

access_log {
        filename /dev/stdout
        priority notice
}

error_log {
        filename /dev/stderr
}

listener 0.0.0.0:443 {
        protocol tls
}

table {
        ^edge\.steam-dns\.top\.comcast\.net$ 127.0.0.1 4433
        .* *:443
}
```

It would be extremely beneficial if we could have environmental variables that added blackhole domains to the config upon container creation. This would fix a lot of the Comcast issues.

**Comment by Lepidopterist** [comment]
Hopefully, the latest changes in the Steam client, whereby it checks the 'trigger domain' of lancache.steamcontent.com should fix this behaviour.

Please can you retest with the latest monolithic + dns + cache domains list and let us know if this is still an issue?

Many thanks

**Comment by miketweaver** [comment]
After additional testing, this issue has gone away with the addition of lancache.steamcontent.com
