### ISSUE TITLE
Docker cannot start sniproxy

### ISSUE THREAD

**Issue by adamradocz** [lancachenet/sniproxy#5]
The steamcache/generic, steamcache-dns and sniproxy use the 192.168.0.101 IP address. The steamcache and steamcache-dns work correctly but the sniproxy gives the following error message:
`ERROR: for sniproxy  Cannot start service sniproxy: driver failed programming external connectivity on endpoint sniproxy: Error starting userland proxy: listen tcp 192.168.0.101:443: bind: address already in use`

The netstat doesn't show any service that uses 192.168.0.101:443.
```
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      0          30677      5620/nginx: master
tcp        0      0 192.168.0.100:40506     172.104.133.220:443     ESTABLISHED 1000       31337      5380/Plex Media Ser
tcp       32      0 192.168.0.100:38090     34.246.147.206:443      CLOSE_WAIT  1000       32008      5556/Plex DLNA Serv
tcp        0      0 192.168.0.100:40508     172.104.133.220:443     ESTABLISHED 1000       31343      5380/Plex Media Ser
```

**Comment by JasonRivers** [comment]
You have a service listening on 0.0.0.0:443 - This will listen on all IP addresses on the system.
You should restrict whatever service you have running on port 443 on all IPs to a specific IP address (or disable the service if it's not needed)

**Comment by adamradocz** [comment]
Thanks for the info. What should I do if the Letsencrypt also uses the 443 port?

**Comment by JasonRivers** [comment]
Use a different IP ADDRESS. Nothing on the caching system requires let's encrypt to run.
