### ISSUE TITLE
I get an error since latest update.

### ISSUE THREAD

**Issue by b11p** [lancachenet/sniproxy#9]
I have been using this image for months, but I get an error since latest update.
I use the following command to run container.
```
docker run --name sniproxy -it --restart always -p 80:80 -p 443:443 -v /root/sniproxy/sniproxy.conf:/etc/sniproxy.conf steamcache/sniproxy:latest
```
However, I get an error like this:
```
sed: can't move '/etc/sniproxy.confDHdAdO' to '/etc/sniproxy.conf': Resource busy
```
It seems something wrong if I map the configure file into container, but it is very important to me. Could you please fix this problem?

**Comment by JasonRivers** [comment]
The last update to SNIproxy was 5 months ago, This image isn't really designed for you to change the config file for, which is why you're seeing the error. Is there a reason you're trying to overwrite the sniproxy.conf file?

**Comment by b11p** [comment]
The main reason is that I'd like to restrict domains allowed in my proxy, and provide web service by specifying domains and IP addresses in `table` section. Moreover, I prefer to use IPv6 first while resolving, but this is nonessential.

**Comment by fanthos** [comment]
Seems that using sed with `-c -i` should fix this error.
